spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quartz?serverTimezone=UTC
    username: root
    password: root
  application:
    name: quartz-cluster-node-first
server:
  port: 8081
#日志打印
logging:
  config: src/main/resources/logback-spring.xml
  level:
    root: INFO
